### PR TITLE
New bitshuffle functions

### PR DESCRIPTION
**Pull request by FrancescAlted**
Here it is a new implementation of bitshuffle for AVX512 coming from [upstream](https://github.com/kiyo-masui/bitshuffle).  I also took the opportunity to sync the SSE2, AVX2 and ARM/NEON implementions (however, the latter is still pretty much slower than the generic solution, so it is not enabled by default).

Preliminary results using AVX512 on Zen4 (AMD 7950X) points to an speed-up of 10% to 15%, which is quite good (most specially as [Zen4 does not have a full 512-bit register implementation](https://www.anandtech.com/show/21092/amd-unveils-ryzen-threadripper-7000-family-zen-4-for-workstations-and-hedt)).

Finally, AVX512 codepath will be compiled by default on UNIX platforms (still need to figure out which MSVC version supports AVX512), and will be used when AVX512 (more specifically AVX512F *and* AVX512BW) presence should be detected in runtime.

### CODE REVIEW

**Comment by FrancescAlted** [comment]
This should be mostly ready, but for some reason, [fuzzing is failing in CI](https://github.com/Blosc/c-blosc2/actions/runs/6689549831/job/18173265834).  I have tried to reproduce that in my Ubuntu box, but I cannot.  Also, valgrind seems fine for the dataset causing the issue to the `compress_chunk_fuzzer`.  I am curious on whether this is a genuine problem, or we should ignore it.  @nmoinvaz can you shed some light on this one? If you cannot reproduce it either, can you suggest a workaround to avoid the failure in CI?

**Comment by nmoinvaz** [comment]
Log shows the input that causes the crash is base64 `HR2dnZ3///////////////89////////////EyvuU/////8=`. You so how to decode it and feed that decoded file into the `compress_chunk_fuzzer`

**Comment by FrancescAlted** [comment]
Yes, I did exacly that, but I am unable to reproduce the issue:

```
$ base64 -d > input.fuz
HR2dnZ3///////////////89////////////EyvuU/////8=
$ build/tests/fuzz/compress_chunk_fuzzer input.fuz
Running 1 inputs
Running: build/tests/fuzz/compress_chunk_fuzzer input.fuz
Done:    input.fuz: (35 bytes)
$ echo $?
0
```

Am I missing something?

**Comment by nmoinvaz** [comment]
I haven't tried it but I can later. Interesting it fails in `blosc_get_cpu_features`. Perhaps those Google fuzzing CI machines don't have AVX512 support?

**Comment by nmoinvaz** [comment]
It doesn't look like you are doing anything controversial in that function.

**Comment by FrancescAlted** [comment]
This is what I think.  Do you know if there is a way to silence the error and treat it as a false positive?

**Comment by nmoinvaz** [comment]
- I can't reproduce it on a machine that supports AVX-512. I tried x86 and x64 build on MSVC.
- I don't know of a way to disable a particular input in the OSS-Fuzz CI.
- `set(COMPILER_SUPPORT_AVX512 TRUE)` is missing for MSVC branch in CMake.
- zlib-ng 2.1.x supports AVX-512 but the version 2.0.x you are using doesn't.

**Comment by FrancescAlted** [comment]
> Here are some of my findings:
> 
> * I can't reproduce it on a machine that supports AVX-512. I tried x86 and x64 build on MSVC.
> * I don't know of a way to disable a particular input in the OSS-Fuzz CI.
> * `set(COMPILER_SUPPORT_AVX512 TRUE)` is missing for MSVC branch in CMake.

Right. Done in 5cd384c9.  And hey! this [seems to fix the OSS-Fuzz issue](https://github.com/Blosc/c-blosc2/actions/runs/6717575741/job/18255680483), although frankly, I don't understand why.

Incidentally, I [also activated a solution based on __builtin_cpu_supports](https://github.com/Blosc/c-blosc2/pull/567/commits/536a0320bcbcfd456c576426e58ed429f9eec580) that works well on modern GCC and Clang compilers.  This looks cleaner than the other based in `__cpuid/_xgetbv` , that still works for MSVC and Intel compilers.

> * zlib-ng 2.1.x supports AVX-512 but the version 2.0.x you are using doesn't.

Yup, I [tried to update to zlib-ng 2.1.x a while ago](https://github.com/Blosc/c-blosc2/pull/553), but still doesn't work.  For more context, see also https://github.com/zlib-ng/zlib-ng/issues/1560. I suppose the solution is close, but I have not figure it out yet.

**Review by ivilata — APPROVED** [review]
LGTM! Congrats on making this work!

**Comment by FrancescAlted** [comment]
I am going to merge this.  BTW, the ALTIVEC implementation for bitshuffle needed a [small API change](https://github.com/Blosc/c-blosc2/pull/567/commits/414b449488b65ab033a234762f88d168c50452ef).  @kif or @t20100 please check this out in a POWER machine when you have the opportunity.  Thanks!

**Comment by FrancescAlted** [comment]
I have done some intensive benchmarks using a AMD 7950X CPU with support for AVX512, and this acceleration seems to work best with fast compressors like LZ4 in compression mode, where up to a 20% faster operation can be seen:

image

It seems that for decompression there is some benefit too, but not as large:

image

All in all, this looks like a nice addition.

**Comment by FrancescAlted** [comment]
For completeness, here are the results for Zstd.  As this is quite more CPU intensive than LZ4, the speedup due to the bitshuffle acceleration is not as evident, but one can still see up to 15% speed-ups:

image

As for decompression, there is almost no difference (and sometimes AVX2 seems to do a better job):

image

**Comment by oscarbg** [comment]
Hi @FrancescAlted ,
I'm on a 7950x, and willing to test.. sorry if noob question, but any simple way (command line launch arguments) to reproduce your findings?..
thanks..

**Comment by FrancescAlted** [comment]
Yes, `b2bench` is the tool that I used to produce the plots (with https://github.com/Blosc/c-blosc2/blob/main/bench/plot-speeds.py).  However, you need to use bitshuffle to see actual accelerations on AVX512 (shuffle does not support AVX512 yet).  On my 7950X3D machine:

```
$ bench/b2bench lz4 bitshuffle suite 32
<snip>
********************** Run info ******************************
Blosc version: 2.10.6.dev ($Date:: 2023-10-05 #$)
Using synthetic data with 19 significant bits (out of 32)
Dataset size: 8388608 bytes	Type size: 4 bytes
Working set: 256.0 MB		Number of threads: 32
********************** Running benchmarks *********************
memcpy(write):		 2356.1 us, 3395.5 MB/s
memcpy(read):		  239.2 us, 33445.5 MB/s
Compression level: 0
comp(write):	  273.0 us, 29301.7 MB/s	  Final bytes: 8388640  Ratio: 1.00
decomp(read):	  202.1 us, 39589.4 MB/s	  OK
Compression level: 1
comp(write):	  223.5 us, 35797.6 MB/s	  Final bytes: 334368  Ratio: 25.09
decomp(read):	  164.2 us, 48725.5 MB/s	  OK
Compression level: 2
comp(write):	  142.8 us, 56020.6 MB/s	  Final bytes: 297760  Ratio: 28.17
decomp(read):	  160.9 us, 49724.9 MB/s	  OK
Compression level: 3
comp(write):	  134.2 us, 59609.9 MB/s	  Final bytes: 275936  Ratio: 30.40
decomp(read):	  170.7 us, 46861.0 MB/s	  OK
Compression level: 4
comp(write):	  156.2 us, 51218.7 MB/s	  Final bytes: 108592  Ratio: 77.25
decomp(read):	  121.7 us, 65730.7 MB/s	  OK
Compression level: 5
comp(write):	  156.3 us, 51196.3 MB/s	  Final bytes: 108592  Ratio: 77.25
decomp(read):	  134.8 us, 59337.6 MB/s	  OK
Compression level: 6
comp(write):	  191.1 us, 41860.8 MB/s	  Final bytes: 102088  Ratio: 82.17
decomp(read):	  150.8 us, 53056.4 MB/s	  OK
Compression level: 7
comp(write):	  188.0 us, 42552.3 MB/s	  Final bytes: 102088  Ratio: 82.17
decomp(read):	  156.5 us, 51131.4 MB/s	  OK
Compression level: 8
comp(write):	  188.8 us, 42378.3 MB/s	  Final bytes: 102088  Ratio: 82.17
decomp(read):	  137.3 us, 58267.1 MB/s	  OK
Compression level: 9
comp(write):	  189.9 us, 42125.4 MB/s	  Final bytes: 102088  Ratio: 82.17
decomp(read):	  167.7 us, 47711.1 MB/s	  OK

Round-trip compr/decompr on 80.0 GB
Elapsed time:	    8.7 s, 20726.4 MB/s
```

**Comment by t20100** [comment]
Hi,

I updated `c-blosc2` to 2.11.1 in `hdf5plugin`: It builds and tests pass on `ppc64le`.

**Comment by oscarbg** [comment]
> Yes, `b2bench` is the tool that I used to produce the plots (with https://github.com/Blosc/c-blosc2/blob/main/bench/plot-speeds.py). However, you need to use bitshuffle to see actual accelerations on AVX512 (shuffle does not support AVX512 yet). On my 7950X3D machine:
> 
> ```
> $ bench/b2bench lz4 bitshuffle suite 32
> <snip>
> ********************** Run info ******************************
> Blosc version: 2.10.6.dev ($Date:: 2023-10-05 #$)
> Using synthetic data with 19 significant bits (out of 32)
> Dataset size: 8388608 bytes	Type size: 4 bytes
> Working set: 256.0 MB		Number of threads: 32
> ********************** Running benchmarks *********************
> memcpy(write):		 2356.1 us, 3395.5 MB/s
> memcpy(read):		  239.2 us, 33445.5 MB/s
> Compression level: 0
> comp(write):	  273.0 us, 29301.7 MB/s	  Final bytes: 8388640  Ratio: 1.00
> decomp(read):	  202.1 us, 39589.4 MB/s	  OK
> Compression level: 1
> comp(write):	  223.5 us, 35797.6 MB/s	  Final bytes: 334368  Ratio: 25.09
> decomp(read):	  164.2 us, 48725.5 MB/s	  OK
> Compression level: 2
> comp(write):	  142.8 us, 56020.6 MB/s	  Final bytes: 297760  Ratio: 28.17
> decomp(read):	  160.9 us, 49724.9 MB/s	  OK
> Compression level: 3
> comp(write):	  134.2 us, 59609.9 MB/s	  Final bytes: 275936  Ratio: 30.40
> decomp(read):	  170.7 us, 46861.0 MB/s	  OK
> Compression level: 4
> comp(write):	  156.2 us, 51218.7 MB/s	  Final bytes: 108592  Ratio: 77.25
> decomp(read):	  121.7 us, 65730.7 MB/s	  OK
> Compression level: 5
> comp(write):	  156.3 us, 51196.3 MB/s	  Final bytes: 108592  Ratio: 77.25
> decomp(read):	  134.8 us, 59337.6 MB/s	  OK
> Compression level: 6
> comp(write):	  191.1 us, 41860.8 MB/s	  Final bytes: 102088  Ratio: 82.17
> decomp(read):	  150.8 us, 53056.4 MB/s	  OK
> Compression level: 7
> comp(write):	  188.0 us, 42552.3 MB/s	  Final bytes: 102088  Ratio: 82.17
> decomp(read):	  156.5 us, 51131.4 MB/s	  OK
> Compression level: 8
> comp(write):	  188.8 us, 42378.3 MB/s	  Final bytes: 102088  Ratio: 82.17
> decomp(read):	  137.3 us, 58267.1 MB/s	  OK
> Compression level: 9
> comp(write):	  189.9 us, 42125.4 MB/s	  Final bytes: 102088  Ratio: 82.17
> decomp(read):	  167.7 us, 47711.1 MB/s	  OK
> 
> Round-trip compr/decompr on 80.0 GB
> Elapsed time:	    8.7 s, 20726.4 MB/s
> ```

thanks for details.. my setup is nearly identical in perf..

**Pull request merged**
