### PR TITLE
Documentation maintenance

### PR DESCRIPTION
**Pull request by oscargm98**

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Good amount of fixes!  Is that ready for merging or you prefer to wait for more to come?

**Comment by oscargm98** [comment]
Better wait a little, there are some files I still would like to check.

**Comment by oscargm98** [comment]
At https://github.com/Blosc/c-blosc2/blob/documentation/doc/sphinx/source/reference/index.rst
there is a reference to "63-bit data containers", is this ok or was it supposed to be "64-bit data containers"?

**Comment by FrancescAlted** [comment]
> At https://github.com/Blosc/c-blosc2/blob/documentation/doc/sphinx/source/reference/index.rst
> there is a reference to "63-bit data containers", is this ok or was it supposed to be "64-bit data containers"?

This is kind of ok. It is actually 63-bit, but it is much more common to refer to this as 64-bit. So maybe using 64 is more consistent.

**Review by aleixalcacer — APPROVED** [review]

**Review by FrancescAlted — APPROVED** [review]

**Pull request merged**
