### PR TITLE
Fixed ASAN heap-buffer-overflow from read trailer outside of frame.

### PR DESCRIPTION
**Pull request by nmoinvaz**
https://oss-fuzz.com/testcase-detail/5143072323272704

### CODE REVIEW

**Comment by nmoinvaz** [comment]
It seems `frame_update_trailer` fails on `trailer_offset + trailer_len > frame->len` which in `test_copy` is `127 > 117`. Off-by-ten. So this could be a bug.

**Comment by nmoinvaz** [comment]
Got it fixed now.

**Review by FrancescAlted — CHANGES_REQUESTED** [review]
Looks good. I just have a couple of suggestions.

**Comment by aleixalcacer** [comment]
The requested changes are already fixed. I'm going to merge the pull.

**Pull request merged**
