### PR TITLE
Patch armv7l shuffle/bitshuffle support include header, lax-vector-conv

### PR DESCRIPTION
**Pull request by mkitti**
This patch resolves the armv7l build issues identified in #306

### CODE REVIEW

**Comment by mkitti** [comment]
1. Subsequent `set_source_files_properties` calls in CMake override previous calls, so `-flax-vector-conversions` needs to be repeated.
2. `#include <sys/auxv.h>` is needed for `getauxval(AT_HWCAP) & HWCAP_ARM_NEO`.

The above allows crosscompiling via BinaryBuilder.

**Comment by mkitti** [comment]
Update coming on this...

**Comment by mkitti** [comment]
Updated

**Comment by mkitti** [comment]
Our BinaryBuilder crosscompiler builds on all of our supported platforms: https://github.com/JuliaPackaging/Yggdrasil/runs/2624565172

**Comment by mkitti** [comment]
I added 54654ac since the prior commit was failing on aarch64-apple-darwin, which is still experimental for us.

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=11102&view=logs&jobId=b73de0a3-cc76-51c8-66e8-3220d54371bd&j=b73de0a3-cc76-51c8-66e8-3220d54371bd&t=f2334286-2aa2-54d4-6f03-edd7fb9da34e

**Comment by mkitti** [comment]
The code in https://github.com/Blosc/c-blosc2/blob/c7071132b69d976510c255b8c1a823a3516f0d54/internal-complibs/zlib-ng-2.0.3/arch/arm/armfeature.c looks a bit more robust in terms of detecting arm features.

In particular, the Linux specific code (`sys/auxv.h`, `getauxval(AT_HWCAP) & HWCAP_ARM_NEON` ) should be included only if `defined(__linux__)`.

**Comment by mkitti** [comment]
You might also need some version of `arm_has_neon` there:

This block looks like it supports older Linux:
https://github.com/Blosc/c-blosc2/blob/c7071132b69d976510c255b8c1a823a3516f0d54/internal-complibs/zlib-ng-2.0.3/arch/arm/armfeature.c#L45-L49

This block supports non-aarch64 Apple on ARM (aarch32?):
https://github.com/Blosc/c-blosc2/blob/c7071132b69d976510c255b8c1a823a3516f0d54/internal-complibs/zlib-ng-2.0.3/arch/arm/armfeature.c#L51-L54

**Comment by FrancescAlted** [comment]
I am not sure we should touch this because right now the test suite is passing in all your ARM platforms, right?  The only exception is aarch64 on Apple, but then this is interesting because I cannot reproduce that in my MacBook M1 box, which, if I am not wrong looks very similar to yours:

```
> uname -a
Darwin Francescs-MacBook-Air.local 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101 arm64
```

But in case you find they are useful, for all sake send a PR.

**Comment by mkitti** [comment]
Yes, currently everything we are building is passing now that you removed the header, so I do not there is nothing very urgent.

I suspect the issue with the header was using the non-Apple provided `Clang` (as opposed to `AppleClang`) and setting `_XOPEN_SOURCE=600` due to the code below.

https://github.com/Blosc/c-blosc2/blob/a723ef86984309b93a14dc1088fba0b2e61177b4/CMakeLists.txt#L315-L318

I personally do not have any Apple hardware to test on, so I'm reticent to purpose major changes in that direction due the lack of my ability to actually test it beyond looking at the CI.

**Pull request merged**
