### PR TITLE
fixed memory leaks

### PR DESCRIPTION
**Pull request by ihsinme**
the functions has the ability to exit without first clearing the allocated memory.

I propose to fix this error.

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Thanks for providing this @ihsinme !  The fuzzer tests are crashing though.  @nmoinvaz any hints here?

**Comment by nmoinvaz** [comment]
Yes, in `frame_get_metalayers`, the variable `header` should only be freed if `(frame->sdata == NULL)`, otherwise it ends up in a double-free of `frame->sdata`.

**Comment by ihsinme** [comment]
sorry for the inattention.
indeed, memory for header is not allocated in some cases.
I've corrected.

**Comment by ihsinme** [comment]
sorry for this rubbish.
correcting the PR conflict, I most likely attracted many new mistakes into it.

**Comment by FrancescAlted** [comment]
LGTM

**Pull request merged**
