### PR TITLE
Added fuzzers for frame compression and decompression.

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by nmoinvaz** [comment]
It appears there are segfaults because `assert` is used through the frame.c code. That probably needs to change..

**Comment by FrancescAlted** [comment]
Yeah, those asserts were meant to help me during the development phase of the frame, but they should be not necessary anymore.  Can you develop a bit more why these are causing trouble?

**Comment by nmoinvaz** [comment]
Yes, because when the frame fuzzers run with random data it will cause those areas to assert/segfault. Those areas will need to be handled safely and return some error code or NULL.

**Comment by FrancescAlted** [comment]
> Yes, because when the frame fuzzers run with random data it will cause those areas to assert/segfault. Those areas will need to be handled safely and return some error code or NULL. Fuzzers are also run during ctest, and that is where it is failing in CI, because unexpected data is passed.

Do you need some additional input from me or you think you can manage this one yourself?

**Comment by nmoinvaz** [comment]
No additional input is needed, thanks! I can do it when I get time again.

**Comment by nmoinvaz** [comment]
I have changed all the `asserts`, but now CI fuzz is reporting fuzzing issues.

**Comment by nmoinvaz** [comment]
Should be ready for review now that I have fixed all the fuzzing issues.

**Review by FrancescAlted — APPROVED** [review]
This looks awesome.  Thank you Nathan!

**Pull request merged**
