### PR TITLE
Zlib ng

### PR DESCRIPTION
**Pull request by FrancescAlted**
Preliminary attempt to use [zlib-ng](https://github.com/zlib-ng/zlib-ng).

### CODE REVIEW

**Comment by nmoinvaz** [comment]
Need to add binary directory to include directories -- second parameter on `add_subdirectories` is binary directory.

Try this:
```
add_subdirectory(internal-complibs/zlib-ng-2.0.0-RC2 internal-complibs/zlib-ng-2.0.0-RC2)
```
And possibly:
```
include_directories(internal-complibs/zlib-ng-2.0.0-RC2)
```

**Comment by FrancescAlted** [comment]
Thanks @nmoinvaz .  It looks like @aleixalcacer has been able to figure out a solution for C-Blosc2 needs.  Unfortunately, the fuzzer refuses to compile.  Suggestions?

**Comment by nmoinvaz** [comment]
It looks like you are copying the file from the binary dir, but you can also just do:
```
include_directories(${CMAKE_CURRENT_BINARY_DIR}/internal-complibs/zlib-ng-2.0.0-RC2);
```

**Comment by nmoinvaz** [comment]
https://github.com/google/oss-fuzz/pull/5360

**Pull request merged**
